### PR TITLE
added TextBox to write out catched ArgumentException from Regex

### PR DESCRIPTION
**Pull request by MartMet**
this should link to issue Invalid regex #16

### CODE REVIEW

**Comment by CommonLoon102** [comment]
Thanks for your PR, I'm glad you liked the app.
I think we should test the regexes first before starting the search and show an error message in a dialog instead.
`MessageBox.Show(ex.Message, "Regex error", MessageBoxType.Error);`
Adding a readonly textbox can be confusing for the user. That section is not really for showing error messages. If the intention was that the user can copy the error message from there, then it is possible with a simple dialog too. If you press Ctrl+C in a dialog like that, it will copy the error message. When you paste it, it will be like this:
```
---------------------------
Regex error
---------------------------
Invalid pattern '(' at offset 1. Not enough )'s.
---------------------------
OK   
---------------------------
```

I know that this is not a well-known feature, so if copying is important, then I would have a custom dialog where you have a button with a clipboard icon which will copy only the error message.

**Review by CommonLoon102 — CHANGES_REQUESTED** [review]
I'd follow a slightly different approach, see my previous comment.

**Comment by MartMet** [comment]
Thanks for your fast response. I agree with you about the readonly textbox.
It was not my intention that the user can copy the error message rather to
give the user a hint. What do you think about a dynamic changing background
color of regex input and maybe a tooltip which appears when the users
entered a wrong regex?

**Comment by CommonLoon102** [comment]
That would be a fancier way of doing it (compared to a simple error message dialog with an OK button). I don't know how easy to do your proposal with ETO, but if it is, then I say go for it. It would be needed to check though if the tooltip works nicely on all supported platforms. Or at least on Windows and Linux with GTK3.

**Comment by MartMet** [comment]
Iam a little bit busy lately, but i think i will have a look. Thanks for your reply.

**Comment by CommonLoon102** [comment]
I've pushed a commit to your master, but for some reason it is not reflected here. Features/bugfixes should be added to feature branches and nothing should be developed in master.

The other thing I found is that the textbox background color is not changing in GTK3 (tested under Ubuntu 18). Need to figure out some other highlighting option.

**Review by CommonLoon102 — CHANGES_REQUESTED** [review]
Textbox background color changing doesn't work under GTK3. Maybe an issue with ETO?
Also, please create a feature branch with the changes instead and create a separate PR from it, this should be closed and development shouldn't happen in master.

**Comment by CommonLoon102** [comment]
Oh, actually I see that I've pushed the changes to martmet/master in your repo, instead of just master. So this is why it is not here.

**Comment by MartMet** [comment]
Sry my mistake. Thanks for merging. :)

Am Di., 6. Okt. 2020 um 23:16 Uhr schrieb CommonLoon102 <
notifications@github.com>:

**Pull request closed without merging**
